### ISSUE TITLE
package.json & the repository is missing a license

### ISSUE THREAD

**Issue by jstarpl** [tv2/mediatech-logger#37]
What is the license for this package? Neither the NPM registry nor this repository contains any license information. Is this a private package that should not be used outside of the organization?

As-is, this package "poisons" any Open Source project using it with strong copyright essentially making it non-Open Source.

**Comment by KvelaGorrrrnio** [comment]
Thanks for pointing it out. I have added MIT license. It will be present next time it is released.

**Comment by jstarpl** [comment]
Great, thank you for fixing this! :)
